#include "IDirectXSprite.H"
/*
class IDirectXFont {
	public:
		IDirectXFont(void);
		~IDirectXFont(void);

		void Create(LPSTR FileName, int, int, int);
		void Release(void);
		int  PutText(int, int, LPSTR, int TextColor = 255, int OurColor = 0, int f = 0);
	   void PutFrontText(int, int, LPSTR, int TextColor = 255);
		operator LPPALETTEENTRY (void);

		IDirectXSprite Font;
		LPPALETTEENTRY Palette;

		short Width;
		short Height;
};
*/